# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: DxE Photo Frames
description: >- # this means to ignore newlines"
  A simple tool to create framed profile pictures for social media.

# Copy
# Fill in your copy for the title and steps here
# 
title-text: "Show your support on social media!"
step-1: "Upload your photo below."
step-2: "Use the preview to move and scale your photo."
step-3: "Select a frame."
step-4: "Download your new profile photo."
step-5: "Set the photo as your profile picture on social media."
footer-text: "&copy; 2021 Direct Action Everywhere"

# Header Nav Link
#
nav-link: "http://directactioneverywhere.com/donate"
nav-link-text: "Donate"

# Buttons and upload form
# 
upload-text: "Drop files here or click to upload."
download-button-text: "Download profile picture"

# Logo & Favicon
# 
logo: "logo.png"
favicon: "favicon.ico"

# Footer links
# 
footer-links:
  - text: "Support the Right to Rescue"
    link: "http://righttorescue.com"

# Open Graph and Twitter Cards
#
og-title: Get your DxE profile frame
og-description: Show your support for the Right to Rescue
og-url: http://directactioneverywhere.com
og-image: "og-image.png"
og-image-width: 1280
og-image-height: 640
twitter-card: summary_large_image
twitter-description: Create your DxE profile frame
twitter-image: "og-image.png"
twitter-handle: "@dxeverywhere"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - pnpm-lock.yaml
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
  - README.md
  - README-DxE.md
  - docs
